package comp:test-repl-reload;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface comp-test-repl-reload-api {
  add: func(value: u64);
  get: func() -> u64;
}

world comp-test-repl-reload {
  export comp-test-repl-reload-api;
}
